services:
  db:
    image: mariadb:10.3
    volumes:
      - ./data/db-init/:/docker-entrypoint-initdb.d/
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: mydb
  adminer:
    image: adminer
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: db